# Generated by Django 4.2 on 2023-06-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_counter_full', models.CharField(max_length=50)),
                ('schem', models.CharField(max_length=20)),
                ('net_adress', models.IntegerField()),
                ('manuf_number', models.IntegerField()),
                ('manuf_data', models.DateTimeField()),
                ('version_data', models.BigIntegerField()),
                ('klass_react', models.FloatField()),
                ('klass_act', models.FloatField()),
                ('nom_u', models.IntegerField()),
                ('nom_i', models.IntegerField()),
                ('ku', models.IntegerField()),
                ('ki', models.IntegerField()),
                ('koefA', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('adress_last_record', models.IntegerField()),
                ('datetime_adr0', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group_full', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LDPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebViewMercury.dbc')),
            ],
        ),
        migrations.CreateModel(
            name='DBPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('write_status_byte', models.IntegerField()),
                ('period_int', models.IntegerField()),
                ('P_plus', models.IntegerField()),
                ('P_minus', models.IntegerField()),
                ('Q_plus', models.IntegerField()),
                ('Q_minus', models.IntegerField()),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebViewMercury.dbc')),
            ],
        ),
        migrations.CreateModel(
            name='DBIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('CurrentFaze1', models.IntegerField()),
                ('CurrentFaze2', models.IntegerField()),
                ('CurrentFaze3', models.IntegerField()),
                ('CurrentSum', models.IntegerField()),
                ('PowerPFaze1', models.IntegerField()),
                ('PowerPFaze2', models.IntegerField()),
                ('PowerPFaze3', models.IntegerField()),
                ('PowerPFazeSum', models.IntegerField()),
                ('PowerQFaze1', models.IntegerField()),
                ('PowerQFaze2', models.IntegerField()),
                ('PowerQFaze3', models.IntegerField()),
                ('PowerQFazeSum', models.IntegerField()),
                ('PowerSFaze1', models.IntegerField()),
                ('PowerSFaze2', models.IntegerField()),
                ('PowerSFaze3', models.IntegerField()),
                ('PowerSFazeSum', models.IntegerField()),
                ('KPowerFaze1', models.IntegerField()),
                ('KPowerFaze2', models.IntegerField()),
                ('KPowerFaze3', models.IntegerField()),
                ('KPowerFazeSum', models.IntegerField()),
                ('EnergyTarif1', models.IntegerField()),
                ('EnergyTarif2', models.IntegerField()),
                ('EnergyTarif3', models.IntegerField()),
                ('EnergyTarif4', models.IntegerField()),
                ('EnergyTarifSum', models.IntegerField()),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebViewMercury.dbc')),
            ],
        ),
        migrations.CreateModel(
            name='DBGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebViewMercury.dbc')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebViewMercury.dbg')),
            ],
        ),
        migrations.AddField(
            model_name='dbc',
            name='group',
            field=models.ManyToManyField(through='WebViewMercury.DBGC', to='WebViewMercury.dbg'),
        ),
    ]
