# Generated by Django 4.2 on 2023-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebViewMercury', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbc',
            name='group',
            field=models.ManyToManyField(through='WebViewMercury.DBGC', to='WebViewMercury.dbg', verbose_name='Наименование группы'),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='manuf_data',
            field=models.DateTimeField(verbose_name='Дата изготовление'),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='manuf_number',
            field=models.IntegerField(verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='name_counter_full',
            field=models.CharField(max_length=50, verbose_name='Наименование счетчика'),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='net_adress',
            field=models.IntegerField(verbose_name='Сетевой адрес'),
        ),
    ]
