# Generated by Django 4.2 on 2023-07-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebViewMercury', '0002_alter_dbc_group_alter_dbc_manuf_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbc',
            options={'verbose_name': 'Счетчик', 'verbose_name_plural': 'Счетчики'},
        ),
        migrations.AlterModelOptions(
            name='dbg',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='dbc',
            name='adress_last_record',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='datetime',
            field=models.DateTimeField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='datetime_adr0',
            field=models.DateTimeField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='ki',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='klass_act',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='klass_react',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='koefA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='ku',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='manuf_data',
            field=models.DateTimeField(blank=True, default=0, verbose_name='Дата изготовление'),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='manuf_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='name_counter_full',
            field=models.CharField(default='', max_length=50, verbose_name='Наименование счетчика'),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='net_adress',
            field=models.IntegerField(default=0, verbose_name='Сетевой адрес'),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='nom_i',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='nom_u',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='schem',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='version_data',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
