# Generated by Django 4.2 on 2023-07-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebViewMercury', '0003_alter_dbc_options_alter_dbg_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbc',
            name='datetime',
            field=models.DateTimeField(blank=True, default='2000-01-01T00:00'),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='datetime_adr0',
            field=models.DateTimeField(blank=True, default='2000-01-01T00:00'),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='manuf_data',
            field=models.DateTimeField(blank=True, default='2000-01-01T00:00', verbose_name='Дата изготовление'),
        ),
    ]
