# Generated by Django 4.2 on 2023-08-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebViewMercury', '0005_alter_dbgc_counter_alter_dbgc_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbc',
            old_name='group',
            new_name='groupes',
        ),
    ]
